const ADD_SUCCESS = 'note/ADD_SUCCESS';
const REMOVE_SUCCESS = 'note/REMOVE_SUCCESS';
const TOGGLE_COMPLETED_SUCCESS = 'note/TOGGLE_COMPLETED_SUCCESS';
const FILTERED = 'note/FILTERED';

const FETCH_REQUEST = 'notes/FETCH_REQUEST';
const FETCH_SUCCESS = 'notes/FETCH_SUCCESS';
const FETCH_ERROR = 'notes/FETCH_ERROR';

export default {
  ADD_SUCCESS,
  REMOVE_SUCCESS,
  TOGGLE_COMPLETED_SUCCESS,
  FILTERED,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_ERROR,
};
